<!-- Hero Section -->
<section class="hero-section">
  <div class="hero-content">
    <h1 class="hero-title">Your Name Here</h1>
    <p class="hero-description">
      Intro text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    </p>
    <a href="#get-started" class="cta-button">Let’s get started ></a>
  </div>
  <div class="hero-image">
    <img src="profile-picture.jpg" alt="Your Photo" />
  </div>
</section>

/* Hero Section */
.hero-section {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 50px 20px;
  background-color: #000;
}

.hero-content {
  max-width: 600px;
  animation: fadeInLeft 1.5s ease-out;
}

.hero-title {
  font-size: 3rem;
  font-weight: bold;
  margin-bottom: 20px;
}

.hero-description {
  font-size: 1.2rem;
  margin-bottom: 30px;
  animation: fadeInUp 2s ease-out;
}

.cta-button {
  display: inline-block;
  padding: 10px 20px;
  font-size: 1rem;
  color: #fff;
  background-color: #00ff7f;
  text-decoration: none;
  border-radius: 5px;
  box-shadow: 0 0 10px #00ff7f;
  transition: transform 0.3s ease;
}

.cta-button:hover {
  transform: scale(1.1);
}

.hero-image {
  animation: fadeInRight 2s ease-out;
}

.hero-image img {
  width: 300px;
  border-radius: 50%;
}

/* Animation Keyframes */
@keyframes fadeInLeft {
  from {
    opacity: 0;
    transform: translateX(-50px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

@keyframes fadeInRight {
  from {
    opacity: 0;
    transform: translateX(50px);
  }
  to {
    opacity: 1;
    transform: translateX(0);
  }
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
